services:

  web-api:
    image: bulat12345/shop_web_api:latest
    container_name: shop_web_api
    ports:
      - "5000:5000"
    env_file:
      - ./env/.env.backend
    depends_on:
      - db
    networks:
      - dev
    restart: always

  frontend:
      image: bulat12345/shop_frontend:latest 
      container_name: shop_frontend
      ports:
        - "80:80"
      env_file:
      - ./env/.env.frontend
      networks:
      - dev
      restart: always

  db:
    image: postgres:latest
    container_name: shop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev
    restart: always
  
volumes:
  postgres_data:

networks:
  dev:
    driver: bridge
